### ISSUE TITLE
There is a typo in the folder name 'script' in README.md

### ISSUE THREAD

**Issue by sociengineer** [aws-samples/amazon-sagemaker-built-in-algorithms-mlops-pipeline-using-aws-cdk#4]
Hello, Kwonyul.
I appreciate your effort in providing this nice CDK asset.

README.md has a little typo. 
The folder's name is "script," without the final s.

The following section of instruction needs be modified:

For more details, open _script_/setup_initial.sh file.
sh _script_/setup_initial.sh config/app-config-demo.json

sh _script_/deploy_stacks.sh config/app-config-demo.json

I hope it would be helpful for your nice asset.

Thank you

Wookjae

**Comment by kwonyulchoi** [comment]
[sociengineer](https://github.com/sociengineer),

Thanks for your comments. I fixed that.

Thanks again.
